# Secret with admin credentials (if not using existing)
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-creds
  namespace: keycloak
  labels:
    app: keycloak
type: Opaque
stringData:
  password: "changeme123!"