---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-creds
  namespace: keycloak
spec:
  encryptedData:
    password: AgBzyoaEPbYeSp4Xtu5N/qd0S80NlJ62V+vook5rAHCi6H+QcDwVos5UjE1uSsx6D1H4Aqc6jdPabmMuG2zkak1Fq8D94je1tVUw4O13VmylKPtbvxikhcXGT8zn2FfWGyRhIINsqkrAIcpE4XvsbM3ng6GQ3CqM/28EXVYfAGCiN+VvWwDehfLGYdNFSVc5vK/iYXJ9figl7XvtcWc9vqmmq/a2WBYFPsqV9S/0gD6ND0dYc17L9lOfLjbCYaTn/DeEdprfUj6+obcvUZzYVLMUVGUb7N9UW/BFVsLtSeuk3SaR2p7q+7gmlwahKKI+Cx4qmWvtdoYSEqRsn2eK3pI081rz0hTTh5HmYA4k94GDG+eYtY0FLvzazzIIWuucGrAHmVAdjtpDS6UceIjOnY56LxGVgNoGTf6lyuMYFWwPCvq/oIKqiX+c9FNMKxA5pFqWG5g4wQpJF21enqDUQWLOJ5QWaAFqyHBHlwlfpaSZn8dtpdw9kg9TEHA7TTfuv/A6v9ADsBZSFWCyqPywNkPLdxPL7bXwNLJWak3Co9Jx++V9fU/ZGUseNZ50wZFwIIqDGfGPpmpA0BesdPXCOcFhIqieNucVRZGSjI/EwmX4hjCV0Q/R+aa0fZtwhUMg/nYDq+ysN7DbvuMRH2r+/xGCm97SXTc1EMVetphr42TgQR3sI/QdOXUA8JVnq9wNYoLPISp3QgND0/iaPTw=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-creds
      namespace: keycloak
